"""empty message

Revision ID: 253da86d4c08
Revises: e7eae392250d
Create Date: 2022-12-16 11:19:40.217453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253da86d4c08'
down_revision = 'e7eae392250d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breakfast', sa.Column('upvotes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('breakfast', 'upvotes')
    # ### end Alembic commands ###
