"""empty message

Revision ID: e7eae392250d
Revises: 29fe4f597c07
Create Date: 2022-12-16 10:31:50.612358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7eae392250d'
down_revision = '29fe4f597c07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('ingredients_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ingredient_name', sa.String(), nullable=True),
    sa.Column('ingredient_quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ingredients_id')
    )
    op.add_column('breakfast', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('breakfast', 'description')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
